version: 2

sources:
  - name: raw_data_04
    description: "Raw data from quality management system"
    schema: raw_data_04
    tables:
      - name: quality_audits
        description: "Raw audit data from quality management system"
        columns:
          - name: audit_id
            description: "Unique identifier for each audit"
            tests:
              - unique
              - not_null
          - name: audit_date
            description: "Date when the audit was conducted"
            tests:
              - not_null
          - name: auditor_name
            description: "Name of the auditor who conducted the audit"
            tests:
              - not_null
          - name: department
            description: "Department that was audited"
            tests:
              - not_null
          - name: compliance_score
            description: "Compliance score from 0 to 100"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 100
          - name: non_conformities_count
            description: "Number of non-conformities found"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: critical_issues
            description: "Number of critical issues found"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
          - name: minor_issues
            description: "Number of minor issues found"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
