quality_management_external:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: dbt_user
      password: dbt_password
      port: 5432
      dbname: dbt_transformed
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
