quality_management_external:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: postgres
      password: post1616!
      port: 5432
      dbname: superstore
      schema: marts_04
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
