name: 'quality_management_dbt_local'
version: '1.0.0'
config-version: 2

profile: 'quality_management_local'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  quality_management_dbt_local:
    staging:
      +materialized: view
    marts:
      +materialized: table
